# Generated by Django 4.2.8 on 2024-01-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_easywin', '0002_customer_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='check_box',
            field=models.CharField(default='-', max_length=10),
            preserve_default=False,
        ),
    ]
